---
# roles/post/tasks/creds.yml
- name: writing deployment credentials locally
  blockinfile:
    path: "/home/{{ sudo_username }}/.credentials"
    create: yes
    owner: "{{ sudo_username }}"
    group: "{{ sudo_username }}"
    mode: 0644
    block: |
      # system user
      sudo username: {{ sudo_username }}
      sudo password: {{ sudo_username_pass }}
      
      # spark user
      spark user: {{ spark_user }}
      spark ui password: {{ spark_ui_password }}
