---
# motd and creds gen

- name: copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd

- name: writing creds into file
  copy:
    dest: "/home/{{ sudo_username }}/.credentials"
    mode: '0600'
    owner: "{{ sudo_username }}"
    group: "{{ sudo_username }}"
    content: |
      sudo username: {{ sudo_username }}
      sudo password: {{ sudo_username_pass }}
      spark user: {{ spark_user }}
      spark ui password: {{ spark_ui_password }}